# Generated by Django 4.1.1 on 2022-10-04 07:24

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False),
        ),
    ]
