# Generated by Django 4.1.1 on 2022-10-04 07:27

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0002_alter_admission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_no',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', editable=False, length=9, max_length=9, prefix='', verbose_name='Student Number'),
        ),
    ]
